<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */

return [
    'Body' => 'Тело',
    'Create email template' => 'Создать email-шаблон',
    'create new template' => 'создать новый шаблон',
    'Create template' => 'Создать шаблон',
    'Create' => 'Создать',
    'Delete' => 'Удалить',
    'email template - {key}' => 'email-шаблон - {key}',
    'Email templates list' => 'Список email-шаблонов',
    'Email templates' => 'Email шаблоны',
    'Error: template was not removed' => 'Ошибка: шаблон не был удален',
    'Hint' => 'Подсказка',
    'Key' => 'Ключ',
    'list of templates' => 'список шаблонов',
    'Removed successfully' => 'Шаблон успешно удален',
    'Save' => 'Сохранить',
    'Update email template - {key}' => 'Обновить email-шаблон - {key}',
    'update template' => 'обновление шаблона',
    'Update' => 'Обновить',
    'view template' => 'обзор шаблона',
    'Subject' => 'Тема',
];